secretsdir=/tmp/secrets
mkdir -p $secretsdir
echo $MONGO_INITDB_ROOT_DATABASE > $secretsdir/MONGO_INITDB_ROOT_DATABASE
echo $MONGO_INITDB_ROOT_USERNAME > $secretsdir/MONGO_INITDB_ROOT_USERNAME
echo $MONGO_INITDB_ROOT_PASSWORD > $secretsdir/MONGO_INITDB_ROOT_PASSWORD
echo $MODUS_SESSION_DATABASE > $secretsdir/MODUS_SESSION_DATABASE
echo $MODUS_SESSION_USERNAME > $secretsdir/MODUS_SESSION_USERNAME
echo $MODUS_SESSION_PASSWORD > $secretsdir/MODUS_SESSION_PASSWORD
echo $MODUS_DATABASE > $secretsdir/MODUS_DATABASE
echo $MODUS_USERNAME > $secretsdir/MODUS_USERNAME
echo $MODUS_PASSWORD > $secretsdir/MODUS_PASSWORD
